title: YR's Homepage
page-top-title: YuRen Wang
top-section-bg-text: Computer Science (AI & DS)
home-subtitle: 王昱人&ensp;|&ensp;YuRen Wang
copyright-text: '&copy; YuRen Wang 2026. All Rights Reserved.'
