title: YR's Homepage
page-top-title: YuRen Wang
top-section-bg-text: Computer Science (AI & DS)
home-subtitle: YuRen Wang&ensp;|&ensp;王昱人
copyright-text: '&copy; YuRen Wang 2026. All Rights Reserved.'
